wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    code_path: code/train_RF.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.7
    start_time: 1647816376
    t:
      1:
      - 1
      - 5
      - 41
      2:
      - 1
      - 5
      - 41
      4: 3.9.7
      5: 0.12.11
      8:
      - 2
      - 5
depth:
  desc: null
  value: 15
mode:
  desc: null
  value: classification
state:
  desc: null
  value: 2000
trees:
  desc: null
  value: 10
