wandb_version: 1

C:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    code_path: code/NeuralCollapse/Vision/neuralcollapse_run.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.7
    start_time: 1652388170
    t:
      1:
      - 1
      - 41
      3:
      - 15
      4: 3.9.7
      5: 0.12.11
      8:
      - 2
      - 5
batch_size:
  desc: null
  value: 128
dataset:
  desc: null
  value: MNIST
dataset_mean:
  desc: null
  value:
  - 0.1307
dataset_std:
  desc: null
  value:
  - 0.3081
epochs:
  desc: null
  value: 350
im_size:
  desc: null
  value: 28
input_ch:
  desc: null
  value: 1
layers:
  desc: null
  value:
  - fc
  - avgpool
  - layer4
  - layer3
  - layer2
  - layer1
model_conf:
  desc: null
  value:
    lr: 0.00959692
    model_name: resnet18
padded_im_size:
  desc: null
  value: 32
use_consistency_loss:
  desc: null
  value: false
