wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    code_path: code/train_RF_wine.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.7
    start_time: 1649869464
    t:
      1:
      - 1
      - 5
      - 41
      2:
      - 1
      - 5
      - 41
      3:
      - 15
      4: 3.9.7
      5: 0.12.11
      8:
      - 2
      - 5
