wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    code_path: code/train_convnet.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.7
    start_time: 1647799922
    t:
      1:
      - 1
      - 41
      4: 3.9.7
      5: 0.12.11
      8:
      - 2
      - 5
